### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by jpandeinge** [stoiclb/elaka#1]
it would be nice to create a thoroughly documentation on how to run the app so it will be easier for those that want to contribute to do so

**Comment by axelmukwena** [comment]
You’re definitely right. I put that on hold long ago when I was still building up the app but just forgot. Will send a notification when all is done

**Comment by axelmukwena** [comment]
I have set up simple reproducible documentation just to get things started. I'll continue to document the entire logic of the app or at least the important sections of it as time goes by. I'll close this issue now, thank you.
